# Generated by Django 5.2.3 on 2025-06-29 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_listings_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='categorie',
            field=models.CharField(blank=True, choices=[('ELC', 'Electronics'), ('FUR', 'Furniture'), ('BOK', 'Books'), ('CLO', 'Clothing'), ('OTH', 'Other')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing', to='auctions.bid'),
        ),
    ]
