# Generated by Django 5.2.3 on 2025-06-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_listing_categorie_listing_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='categorie',
            new_name='category',
        ),
    ]
